# Generated by Django 2.1.8 on 2020-02-26 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='description',
        ),
    ]
